AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs8.10
    Timeout: 5
Resources:
  eventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: MyBucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://john-sam/038faa88b588f6c7ae2908f4b604799f
  MyBucket:
    Type: AWS::S3::Bucket
  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post
      CodeUri: s3://john-sam/038faa88b588f6c7ae2908f4b604799f
